config/routes.rb
Rails.application.routes.draw do

  get 'report' => 'report#index'

  devise_for :users, skip: [:registrations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :tasks do
    resources :comments, only: [:create, :new]
  end

  resources :users do
    resources :messages, only: [:new, :create]
  end

  resource :profile, only: [:edit, :update]
  resource :geolocation, only: [:update]

  root 'tasks#index'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def update
    current_user.update(user_params)
    redirect_to :back, notice: 'Profile updated successfully.'
  end

  #  ===================
  #  = Private methods =
  #  ===================
  private
    def user_params
      params.require(:profile).permit(:name, :phone)
    end

end

app/views/profiles/edit.html.erb
<div class="page-header">
  <h3>Profile</h3>
</div>

<%= simple_form_for current_user, as: :profile, url: profile_path, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <div class="col-xs-4">
      <%= f.input :email, input_html: { disabled: :disabled, class: 'form-control'} %>
      <%= error_span(current_user[:email]) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.input :name, input_html: { class: 'form-control' } %>
      <%= error_span(current_user[:name]) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.input :phone, input_html: { class: 'form-control' } %>
      <%= error_span(current_user[:phone]) %>
    </div>
  </div>

  <br>
  <%= f.button :submit, 'Update', class: 'btn-primary', data: {disable_with: 'Updating...'} %>
<% end %>


<br>

Connect your social accounts

<% provider_names = [] %>
<% current_user.authorizations.each do |authorization| %>
  <% provider_names << authorization.provider %>
  <%= link_to (authorization.provider.upcase), 'javascript:void(0)', class: 'btn btn-info active', title: "Already connected" %>
<% end %>

<% (User.omniauth_providers - provider_names).each do |provider| %>
  <%= link_to provider.upcase, omniauth_authorize_path(:user, provider), class: 'btn btn-primary' %>
<% end %>