config/routes.rb
Rails.application.routes.draw do

  get 'report' => 'report#index'

  devise_for :users, skip: [:registrations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :tasks do
    resources :comments, only: [:create, :new]
  end

  resources :users do
    resources :messages, only: [:new, :create]
  end

  resource :profile, only: [:edit, :update]
  resource :geolocation, only: [:update]

  root 'tasks#index'

end

app/views/layouts/_footer.html.erb
<br><hr>
<footer>
  <p>&copy; Company 2014</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'ManagementPortal', root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <%= content_tag :li, link_to( 'Tasks', tasks_path), class: "#{ 'active' if controller_name == 'tasks' }" -%>
          <%= content_tag :li, link_to( 'Report', report_path), class: "#{ 'active' if current_page?(report_url)}" if current_user.manager? %>
          <%= content_tag :li, link_to( 'Users', users_path), class: "#{ 'active' if controller_name == 'users'}" if current_user.manager_or_data_moderator? %></li>
          <%= content_tag :li, link_to( 'Edit Profile', edit_profile_path), class: "#{ 'active' if current_page?(edit_profile_path)}" %>
          <%= content_tag :li, link_to( "Log out (#{current_user.name})", destroy_user_session_path, method: :delete) %>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Sidebar</h3>
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li><%= link_to "Link1", 'javascript:void(0)'  %></li>
      <li><%= link_to "Link2", 'javascript:void(0)'  %></li>
      <li><%= link_to "Link3", 'javascript:void(0)'  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ManagementPortal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>

  <!--  ========  -->
  <!--  = Body =  -->
  <!--  ========  -->
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <!-- <div class="col-lg-9"> -->
        <div id="bootstrap_flash" class="">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <%#= render 'layouts/sidebar' %>
      </div><!--/row-->

      <%= render 'layouts/footer' %>
    </div> <!-- /container -->

    <%= javascript_tag( 'startNavigator()') if( current_user and current_user.data_collection_executive? ) %>
  </body>

</html>